IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CCCG\Ahayes')
CREATE LOGIN [CCCG\Ahayes] FROM WINDOWS
GO
CREATE USER [CCCG\Ahayes] FOR LOGIN [CCCG\Ahayes] WITH DEFAULT_SCHEMA=[CCCG\Ahayes]
GO
REVOKE CONNECT TO [CCCG\Ahayes]
